name: CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install libzbar
        run: |
          sudo apt update
          sudo apt install libzbar-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libzbar.so /usr/lib
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - stable
          - nightly
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libzbar
        run: |
          sudo apt update
          sudo apt install libzbar-dev
          sudo ln -s /usr/lib/x86_64-linux-gnu/libzbar.so /usr/lib
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build
      - run: cargo build --examples
      - run: cargo test
      - run: cargo doc